# -*- coding: utf-8 -*-
"""Kelompok 2_23F_Analisis Akustik Instrumen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgQ-G7qePyOjVXgkr5RGLacTgSmwlnJ4

# Analisis Perbandingan Karakteristik Akustik Biola Tuned dan Untuned
```
*tuliskan deskripsi proyek di sini*
```
Tujuan utama proyek ini adalah untuk secara mendalam menganalisis dan membandingkan karakteristik akustik dari sebuah biola yang telah disetel (tuned) dengan biola yang belum disetel (untuned).

Aspek-aspek yang akan dibandingkan secara umum meliputi:
*   Frekuensi:
Perbedaan fundamental frekuensi (picth)
*   Intensitas:
Perbedaan volume antara nada-nada yang berbeda.
* Timbre:
Analisis kualitas suara (timbre) berdasarkan intensitas harmonik.
* Noise:
Adanya suara-suara tambahan yang tidak diinginkan, seperti desingan atau bising.
* Perubahan Spektrum: Identifikasi perbedaan spektrum frekuensi untuk masing-masing kondisi biola.

Data ini dapat digunakan untuk mengembangkan algoritma pengenalan instrumen atau analisis musik secara umum.

Sumber Data: [link audio](https://drive.google.com/drive/folders/1Ha1Km89IixDx4pqBdmQDozqyIVuJqyQ-?usp=sharing)



**Anggota Kelompok:**
1.   Widya Louisa (23031554180)
2.   Brilliyanda Annisaatulrohmah (23031554216)
3.  Mutiara Khanza Asyifa (23031554230)

## Akuisisi Data

```
Berikan penjelasan tentang sinyal tersebut.

*   Sinyal apakah itu?
*   Bagaimana sinyal itu diperoleh? Sinyal tersebut menggambarkan kondisi apa?
*   Informasi apa sajakah yang tersimpan pada sinyal tersebut
*   Apa perbedaan sinyal dalam kondisi normal dan abnormal?
```


Sinyal yang dianalisis adalah sinyal akustik (gelombang suara) yang dihasilkan oleh biola. Sinyal diperoleh dengan merekam bunyi biola menggunakan mikrofon dan kemudian menyimpannya dalam format audio digital (.wav). File audio ini kemudian diproses menggunakan pustaka librosa. Sinyal menggambarkan kondisi biola yang dituning dengan nada yang sesuai standar dan juga kondisi biola yang belum dituning.

Sinyal mengandung informasi tentang:
* Amplitude: Menggambarkan kekuatan suara.
* Frekuensi: Mengindikasikan nada dan harmoni.
* Durasi: Panjang waktu bunyi dihasilkan.
* Harmonik dan Noise: Perbandingan antara suara utama dan gangguan/noise.
* Spektrum Frekuensi: Distribusi energi di berbagai frekuensi.

Perbedaan Kondisi Normal dan Abnormal
* Normal (Tuned):
  1. Frekuensi fundamental stabil.
  2. Harmoni lebih dominan dibanding noise.
  3. Spektrum frekuensi menunjukkan distribusi energi pada nada yang sesuai.
* Abnormal (Untuned):
  1. Frekuensi fundamental tidak stabil atau tidak sesuai dengan nada yang diinginkan.
  2. Noise lebih dominan.
  3. Spektrum frekuensi menunjukkan distribusi energi yang lebih acak.

## Visualisasi Sinyal

### Domain Waktu
"""

# Import dan tampilkan sinyal tersebut di sini
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt

# Load audio files
file_tuned = 'Auld Lang Syne Tuning.wav'  # File biola yang sudah dituning
file_untuned = 'Auld Lang Syne Unturned.wav'  # File biola yang belum dituning

# Load audio signals and sampling rates
y_tuned, sr_tuned = librosa.load(file_tuned, sr=None)
y_untuned, sr_untuned = librosa.load(file_untuned, sr=None)

# Plot the waveform
def plot_waveform(y, sr, title):
    plt.figure(figsize=(10, 4))
    librosa.display.waveshow(y, sr=sr)
    plt.title(title)
    plt.xlabel('Time (s)')
    plt.ylabel('Amplitude')
    plt.show()

plot_waveform(y_tuned, sr_tuned, "Waveform - Biola Tuned")
plot_waveform(y_untuned, sr_untuned, "Waveform - Biola Untuned")

"""```
Penjelasan untuk membaca plotting sinyal dalam domain waktu
```
Elemen:
1. Sumbu X (Time):
Menunjukkan durasi sinyal, dari awal hingga akhir rekaman(dalam detik).
2. Sumbu Y (Amplitude):
Nilai amplitudo mencerminkan intensitas atau kekuatan sinyal pada waktu tertentu.
3. Pola:
Pola naik-turun (gelombang) mencerminkan perubahan amplitudo sinyal terhadap waktu.Pola ini menunjukkan bagaimana suara berubah dari waktu ke waktu.

Hasil Plot Biola tuned dan untuned:
- Biola Tuned:
  1. Amplitudo Terdistribusi Merata:
    Pada waveform pertama, amplitudo cenderung konsisten dan terdistribusi merata.
    Ini menunjukkan bahwa biola tuned menghasilkan suara yang stabil dan sesuai nada standar.
  2. Perubahan Amplitudo Teratur:
    Perubahan amplitudo mengikuti pola tertentu, mengindikasikan gelombang sinusoidal yang harmonis.
  3. Pengurangan Noise:
    Amplitudo yang terlihat lebih terpusat menunjukkan pengurangan noise dan peningkatan kualitas suara.

- Biola Untuned:
  1. Amplitudo Lebih Tidak Teratur:
    Pada waveform kedua, amplitudo terlihat lebih acak atau tidak konsisten.
    Ini mengindikasikan adanya noise atau nada yang tidak sesuai.
  2. Pola Amplitudo Berbeda:
    Gelombang cenderung lebih bervariasi dalam intensitas, menunjukkan frekuensi-frekuensi yang tidak harmonis.
  3. Noise Levels:
    Kemungkinan terdapat lebih banyak komponen noise karena biola belum dituning cenderung menghasilkan suara yang tidak terfokus.

### Domain Frekuensi
"""

# Transformasikan sinyal tersebut ke dalam domain frekuensi
# Gunakan modul scipy.fft

from scipy.fft import fft

def plot_fft(y, sr, title):
    fft_result = fft(y)
    magnitude = np.abs(fft_result)
    frequency = np.linspace(0, sr, len(magnitude))

    plt.figure(figsize=(10, 4))
    plt.plot(frequency[:len(frequency)//2], magnitude[:len(magnitude)//2])
    plt.title(title)
    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Magnitude')
    plt.grid()
    plt.show()

plot_fft(y_tuned, sr_tuned, "Frequency Spectrum - Biola Tuned")
plot_fft(y_untuned, sr_untuned, "Frequency Spectrum - Biola Untuned")

"""```
Berikan penjelasan tentang informasi apa saja yang dapat diketahui dari hasil transformasi sinyal tersebut dalam domain frekuensi
```
Elemen Utama dalam Plot Spektrum Frekuensi:
1. Sumbu X (Frequency):
Sumbu horizontal menunjukkan frekuensi dalam satuan Hertz (Hz).
Ini menunjukkan komponen frekuensi yang ada dalam sinyal, dari frekuensi rendah hingga tinggi.
2. Sumbu Y (Magnitude):
Sumbu vertikal menunjukkan magnitudo atau intensitas setiap frekuensi.
Nilai ini merepresentasikan seberapa dominan frekuensi tertentu dalam sinyal.
3. Puncak Frekuensi:
Puncak-puncak dalam grafik menunjukkan frekuensi dominan yang ada dalam sinyal.
Frekuensi dominan adalah nada utama yang terdengar pada biola.

Informasi yang Dapat Diketahui:
1. Frekuensi Dominan:
    Pada Biola Tuned, frekuensi puncak berada di sekitar 100 Hz, tetapi distribusi frekuensi lain lebih terkonsentrasi pada nilai-nilai tertentu dengan amplitude yang lebih stabil, menunjukkan suara yang lebih harmonis. Sedangkan pada Biola Untuned, frekuensi puncak tertinggi juga berada di sekitar 100 Hz, tetapi ada banyak puncak tambahan dan distribusi frekuensi lainnya yang lebih berantakan dan tersebar.
2. Magnitude Maksimum:
    Grafik untuned memiliki magnitudo maksimum sekitar 6000, sedangkan grafik tuned memiliki magnitudo maksimum yang lebih tinggi, sekitar 8000. Ini menunjukkan bahwa setelah biola diselaraskan, sinyalnya lebih kuat dan lebih terfokus.
3. Harmonik:
    Pada grafik biola tuned, frekuensi harmonik tampak lebih bersih dengan puncak yang lebih teratur dibandingkan dengan kondisi untuned, di mana harmonik tampak lebih acak dan berantakan. Ini menandakan bahwa setelah tuning, biola menghasilkan suara yang lebih jernih dan harmonis.
4. Distribusi Frekuensi:
    Pada kondisi untuned, ada distribusi frekuensi yang lebih lebar dan kacau, sedangkan pada kondisi tuned, frekuensi terfokus pada rentang yang lebih spesifik dan teratur.

## Pra-Pemrosesan

```
jelaskan langkah-langkah pra-pemrosesan yang diperlukan untuk mengolah sinyal tersebut. Misalkan filtering, normalisasi, dsb. Sesuaikan dengan kebutuhan tiap proyek.
```
Pra-pemrosesan diperlukan untuk memastikan analisis frekuensi lebih akurat. Berikut adalah langkah-langkah yang dapat dilakukan:

1. DC Removal: Proses menghilangkan komponen frekuensi nol atau rata-rata dari sinyal. Komponen DC ini merupakan noise atau offset yang tidak membawa informasi yang berguna. Dengan menghilangkan DC, kita dapat memfokuskan analisis pada variasi sinyal yang sebenarnya.
2. Filtering: Membuang noise atau memilih rentang frekuensi yang diinginkan. Melakukan penyaringan pita frekuensi tertentu (bandpass filter) pada sinyal. Membantu menonjolkan komponen frekuensi utama dengan menghapus frekuensi di luar rentang yang relevan untuk biola.
3. Pre-Emphasis: Untuk menonjolkan komponen frekuensi tinggi dalam sinyal.
4. Normalisasi: Tujuannya adalah untuk membuat semua data memiliki skala yang sama, sehingga memudahkan perbandingan dan analisis. Proses penskalaan amplitudo sinyal ke rentang -1 dan 1.
"""

import librosa
print("Sampling rate - Biola Tuned:", sr_tuned)
print("Sampling rate - Biola Untuned:", sr_untuned)

"""### DC Removal"""

# DC Removal function
def dc_removal(signal):
    return signal - np.mean(signal)

# Visualize the signal
def plot_signal(signal, title):
    plt.figure(figsize=(10, 4))
    plt.plot(signal)
    plt.title(title)
    plt.xlabel('Samples')
    plt.ylabel('Amplitude')
    plt.grid(True)
    plt.show()

# Apply DC Removal
y_tuned_dc = dc_removal(y_tuned)
y_untuned_dc = dc_removal(y_untuned)

# Visualize before and after DC removal for both signals
plot_signal(y_tuned_dc, 'Tuned Signal After DC Removal')
plot_signal(y_untuned_dc, 'Untuned Signal After DC Removal')

"""### Filtering"""

#Filtering (Penyaringan Frekuensi)

from scipy.signal import butter, lfilter

# Fungsi untuk membuat dan menerapkan bandpass filter
def bandpass_filter(y, lowcut, highcut, sr, order=5):
    nyquist = 0.5 * sr  # Frekuensi Nyquist
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = butter(order, [low, high], btype='band')  # Bandpass filter
    y_filtered = lfilter(b, a, y)  # Aplikasikan filter pada sinyal
    return y_filtered

# Parameter filtering
lowcut = 196  # Frekuensi batas bawah (196 Hz = nada G3 biola)
highcut = 4000  # Frekuensi batas atas (4000 Hz untuk harmonik biola)
order = 5  # Order filter

# Aplikasikan filtering ke sinyal tuned dan untuned
y_tuned_filtered = bandpass_filter(y_tuned_dc, lowcut, highcut, sr=sr_tuned, order=order)
y_untuned_filtered = bandpass_filter(y_untuned_dc, lowcut, highcut, sr=sr_untuned, order=order)

# Plot hasil filtering untuk melihat perbedaannya
plot_fft(y_tuned_filtered, sr_tuned, "Bandpass Filtered Frequency Spectrum - Biola Tuned")
plot_fft(y_untuned_filtered, sr_untuned, "Bandpass Filtered Frequency Spectrum - Biola Untuned")

"""### Pre-emphasize"""

# Pre-emphasize

y_tuned_emp = librosa.effects.preemphasis(y_tuned_filtered)
y_untuned_emp = librosa.effects.preemphasis(y_untuned_filtered)

plot_fft(y_tuned_emp, sr_tuned, "Pre-emphasis - Biola Tuned") # Plotting for y_tuned
plot_fft(y_untuned_emp, sr_untuned, "Pre-emphasis - Biola Untuned") # Plotting for y_untuned

"""### Normalisasi"""

# Normalisasi agar amplitudo berada dalam rentang [-1, 1]
y_tuned_normalized = y_tuned / np.max(np.abs(y_tuned_emp))
y_untuned_normalized = y_untuned / np.max(np.abs(y_untuned_emp))

# Plot ulang spektrum frekuensi setelah normalisasi
plot_fft(y_tuned_normalized, sr_tuned, "Frequency Spectrum - Biola Tuned (Normalized)")
plot_fft(y_untuned_normalized, sr=sr_untuned, title="Frequency Spectrum - Biola Untuned (Normalized)")

import librosa
import soundfile as sf

sf.write("tuned_audio_processed.wav", y_tuned_normalized, sr_tuned)
sf.write("untuned_audio_processed.wav", y_untuned_normalized, sr_untuned)

"""## Ekstraksi Fitur

```
Jelaskan fitur apa yang ingin diekstraksi dan mengapa. Berikan statement pendukung dari artikel terkait
```
- Fitur 1: Frekuensi Fundamental

  Frekuensi fundamental merupakan ciri khas dari sebuah nada dan sangat penting untuk menentukan apakah sebuah instrumen telah disetel dengan benar.  Perbedaan frekuensi fundamental antara biola yang tuned dan untuned akan signifikan.

- Fitur 2: Harmonic-to-Noise Ratio (HNR)

  HNR mengukur rasio antara komponen harmonik dan noise dalam sinyal audio. Biola yang tuned akan memiliki HNR yang lebih tinggi karena harmoniknya lebih dominan dan noise lebih rendah.

- Fitur 3: Mel-Frequency Cepstral Coefficients (MFCC)

  MFCC merepresentasikan spektrum frekuensi dalam skala mel, yang lebih sesuai dengan persepsi pendengaran manusia. MFCC merupakan fitur yang robust terhadap noise dan variasi ucapan/suara.

- Fitur 4: Spectral Centroid

  Spectral centroid menunjukkan titik pusat dari spektrum frekuensi.  Perbedaan spectral centroid antara biola tuned dan untuned dapat menunjukkan perbedaan distribusi energi frekuensi.

- Fitur 5: Spectral Rolloff

  Spectral rolloff menunjukkan frekuensi di bawah mana sebagian besar energi sinyal berada.  Biola yang tuned mungkin memiliki spectral rolloff yang berbeda dibandingkan dengan biola yang untuned.

- Fitur 6: Zero-Crossing Rate (ZCR)

  ZCR mengukur seberapa sering sinyal melintasi nol.  Perbedaan ZCR bisa menunjukkan perbedaan karakteristik suara antara biola tuned dan untuned, meskipun ZCR mungkin bukan indikator utama untuk tuning.

- Fitur 7: RMS Energy (Intensity)
    
  RMS energy merepresentasikan intensitas suara atau volume. Perbedaan intensitas antara biola tuned dan untuned bisa mengindikasikan perbedaan kekuatan sinyal audio.


Statement Pendukung:
- https://www.jstage.jst.go.jp/article/ast/44/3/44_E2280/_article
- https://pubmed.ncbi.nlm.nih.gov/32828526/
- https://www.researchgate.net/profile/Hamdan-Sinin/publication/357426095_The_Frequency_Spectrum_and_Time_Frequency_Analysis_of_Different_Violins_Classification_as_Tools_for_Selecting_a_Good-Sounding_Violin/links/620f33d8eb735c508add77da/The-Frequency-Spectrum-and-Time-Frequency-Analysis-of-Different-Violins-Classification-as-Tools-for-Selecting-a-Good-Sounding-Violin.pdf
- https://pubs.aip.org/asa/poma/article/49/1/035004/2842634/Identification-of-violin-timbre-by-neural-network
- https://mti.binus.ac.id/2017/11/13/ekstraksi-fitur-untuk-genre-musik/?utm_source=chatgpt.com
- https://analyticsindiamag.com/ai-trends/a-tutorial-on-spectral-feature-extraction-for-audio-analytics/

### Fitur 1: Frekuensi Fundamental
"""

# Ekstraksi Frekuensi Fundamental

def extract_fundamental_frequency(y, sr):
    # Gunakan librosa.yin untuk estimasi frekuensi fundamental
    f0, voiced_flag, voiced_probs = librosa.pyin(y, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'))

    # Hitung frekuensi fundamental rata-rata
    fundamental_frequency = np.mean(f0[voiced_flag])

    return fundamental_frequency

# Ekstrak frekuensi fundamental untuk biola tuned dan untuned
fundamental_tuned = extract_fundamental_frequency(y_tuned_normalized, sr_tuned)
fundamental_untuned = extract_fundamental_frequency(y_untuned_normalized, sr_untuned)

print("Frekuensi fundamental biola tuned:", fundamental_tuned, "Hz")
print("Frekuensi fundamental biola untuned:", fundamental_untuned, "Hz")

"""### Fitur 2: Harmonic-to-Noise Ratio"""

# Compare harmonic-to-noise ratio (HNR)
# Dekomposisi sinyal menggunakan STFT untuk memisahkan komponen harmonik dan noise.
def harmonic_to_noise_ratio(y, sr):
    S, phase = librosa.magphase(librosa.stft(y))
    harmonic = librosa.decompose.hpss(S)[0]
    noise = S - harmonic
    hnr = np.sum(harmonic**2) / np.sum(noise**2)
    return 10 * np.log10(hnr)

hnr_tuned = harmonic_to_noise_ratio(y_tuned_normalized, sr_tuned)
hnr_untuned = harmonic_to_noise_ratio(y_untuned_normalized, sr_untuned)

print(f"Harmonic-to-Noise Ratio (HNR):")
print(f"Tuned: {hnr_tuned:.2f} dB")
print(f"Untuned: {hnr_untuned:.2f} dB")

"""### Fitur 3: Mel-Frequency Cepstral Coefficients (MFCC)"""

# Extract MFCC features
def extract_mfcc(signal, sr, n_mfcc=13):
    mfcc = librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=n_mfcc, hop_length=512)
    return mfcc.T

# Compute MFCC features
mfcc_tuned = extract_mfcc(y_tuned_normalized, sr_tuned)
mfcc_untuned = extract_mfcc(y_untuned_normalized, sr_untuned)

print(f"MFCC Shape (tuned): {mfcc_tuned.shape}")
print(f"MFCC Shape (untuned): {mfcc_untuned.shape}")

"""### Fitur 4: Spectral Centroid
Spectral centroid menunjukkan titik pusat dari spektrum frekuensi. Nilai yang lebih tinggi menunjukkan bahwa spektrum lebih condong ke frekuensi yang lebih tinggi.

"""

def spectral_centroid(y, sr):
    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)
    return np.mean(centroid)

centroid_tuned = spectral_centroid(y_tuned_normalized, sr_tuned)
centroid_untuned = spectral_centroid(y_untuned_normalized, sr_untuned)

print(f"Spectral Centroid:")
print(f"Tuned: {centroid_tuned:.2f} Hz")
print(f"Untuned: {centroid_untuned:.2f} Hz")

"""### Fitur 5: Spectral Rolloff
Spectral rolloff menunjukkan frekuensi di bawah mana sebagian besar energi sinyal berada.

"""

def spectral_rolloff(y, sr):
    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    return np.mean(rolloff)

rolloff_tuned = spectral_rolloff(y_tuned_normalized, sr_tuned)
rolloff_untuned = spectral_rolloff(y_untuned_normalized, sr_untuned)

print(f"Spectral Rolloff:")
print(f"Tuned: {rolloff_tuned:.2f} Hz")
print(f"Untuned: {rolloff_untuned:.2f} Hz")

"""### Fitur 6: Zero-Crossing Rate
Zero-crossing rate mengukur seberapa sering sinyal melintasi nol. Ini bisa mengindikasikan karakteristik perkusi atau suara yang lebih tajam.

"""

def zero_crossing_rate(y):
    zcr = librosa.feature.zero_crossing_rate(y)
    return np.mean(zcr)

zcr_tuned = zero_crossing_rate(y_tuned_normalized)
zcr_untuned = zero_crossing_rate(y_untuned_normalized)

print(f"Zero Crossing Rate:")
print(f"Tuned: {zcr_tuned:.2f}")
print(f"Untuned: {zcr_untuned:.2f}")

"""### Fitur 7: RMS Energy"""

import numpy as np

# Compute intensity (RMS energy)
def compute_intensity(audio):
    rms = np.sqrt(np.mean(audio**2))
    return rms

intensity_tuned = compute_intensity(y_tuned_normalized)
intensity_untuned = compute_intensity(y_untuned_normalized)

# Print hasil RMS untuk kedua audio
print(f"Intensity (RMS) for Tuned: {intensity_tuned}")
print(f"Intensity (RMS) for Untuned: {intensity_untuned}")

"""## Analisis

jelaskan langkah-langkah dan hasil analisis dari pengolahan sinyal tersebut. Analisis dapat berupa:
*   Perbandingan kondisi normal dan abnormal
*   Signal-to-Noise-Ratio
*   Sinyal sebelum dan sesudah treatment
*   dst

sesuaikan dengan tujuan pengolahan sinyal

### Analisis 1
"""

print("\nPerbandingan Kondisi Biola Tuned dan Untuned:")
print("---------------------------------------------")
print(f"Frekuensi Fundamental: Tuned = {fundamental_tuned:.2f} Hz, Untuned = {fundamental_untuned:.2f} Hz")
print(f"Harmonic-to-Noise Ratio (HNR): Tuned = {hnr_tuned:.2f} dB, Untuned = {hnr_untuned:.2f} dB")
print(f"Spectral Centroid: Tuned = {centroid_tuned:.2f} Hz, Untuned = {centroid_untuned:.2f} Hz")
print(f"Spectral Rolloff: Tuned = {rolloff_tuned:.2f} Hz, Untuned = {rolloff_untuned:.2f} Hz")
print(f"Zero Crossing Rate: Tuned = {zcr_tuned:.2f}, Untuned = {zcr_untuned:.2f}")
print(f"Intensity (RMS): Tuned = {intensity_tuned:.2f}, Untuned = {intensity_untuned:.2f}")

"""Interpretasi Hasil:

Berdasarkan hasil perhitungan, dapat diamati perbedaan karakteristik antara biola tuned dan untuned.
- HNR yang lebih tinggi pada biola tuned mengindikasikan proporsi harmonik yang lebih besar dibandingkan noise.
- Perbedaan frekuensi fundamental, spectral centroid, dan spectral rolloff juga dapat mencerminkan perbedaan nada dan kualitas suara.
- MFCC memberikan gambaran detail tentang karakteristik timbre suara.
- Analisis lebih lanjut dapat dilakukan dengan membandingkan nilai-nilai MFCC antara kedua kondisi.

### Analisis 2
"""

# Analysis of MFCC results

print("\nMFCC Analysis:")
print("-------------")

# Comparing MFCC means
mfcc_tuned_mean = np.mean(mfcc_tuned, axis=0)
mfcc_untuned_mean = np.mean(mfcc_untuned, axis=0)

print("Mean MFCC values (Tuned):", mfcc_tuned_mean)
print("Mean MFCC values (Untuned):", mfcc_untuned_mean)

# Calculate the difference between MFCC means
mfcc_diff = np.abs(mfcc_tuned_mean - mfcc_untuned_mean)

print("\nDifference in mean MFCC values:", mfcc_diff)

# Identify MFCC coefficients with the largest differences
top_diff_indices = np.argsort(mfcc_diff)[::-1][:5] # Get indices of top 5 differences
print("\nTop 5 MFCC coefficients with largest differences:")
for i in top_diff_indices:
    print(f"Coefficient {i+1}: Difference = {mfcc_diff[i]:.2f}")


# Visualization of MFCC differences (optional)
plt.figure(figsize=(10, 6))
plt.plot(mfcc_tuned_mean, label='Tuned')
plt.plot(mfcc_untuned_mean, label='Untuned')
plt.title('Comparison of Mean MFCC Values')
plt.xlabel('MFCC Coefficient')
plt.ylabel('Value')
plt.legend()
plt.show()

"""MFCC adalah representasi numerik dari spektrum suara manusia yang sering digunakan dalam pengenalan suara dan pemrosesan sinyal audio. Setiap koefisien MFCC mewakili aspek yang berbeda dari suara, seperti nada, timbre, dan informasi prosodik.

Interpretasi Hasil:

- Perbedaan Besar pada Koefisien Tertentu: Fakta bahwa beberapa koefisien MFCC memiliki perbedaan yang sangat besar antara data yang di-tune dan yang tidak di-tune menunjukkan bahwa proses tuning telah mengubah karakteristik suara secara signifikan pada aspek-aspek tertentu.
- Pengaruh Tuning: Proses tuning kemungkinan besar telah mengubah nada, timbre, atau karakteristik lain dari suara, yang tercermin dalam perubahan nilai MFCC.

### Analisis 3
"""

# Compute and plot spectrogram
def plot_spectrogram(y, sr, title):
    D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
    plt.figure(figsize=(10, 6))
    librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log')
    plt.colorbar(format='%+2.0f dB')
    plt.title(title)
    plt.show()

plot_spectrogram(y_tuned_normalized, sr_tuned, "Spectrogram - Biola Tuned")
plot_spectrogram(y_untuned_normalized, sr_untuned, "Spectrogram - Biola Untuned")

"""Perbedaan Visual:
- Spektrogram biola yang telah di-tune menunjukkan distribusi frekuensi yang lebih terorganisir dan fokus.
- Pada biola yang belum di-tune, spektogram mungkin menampilkan banyak noise dan frekuensi yang tidak konsisten, sehingga tampak lebih berantakan.

Interpretasi Fitur:
- Intensitas:  Bagian-bagian yang lebih terang pada spektrogram mengindikasikan frekuensi dengan intensitas yang lebih tinggi. Pada biola yang telah di-tune, intensitas harus terpusat pada harmonik yang diharapkan, sedangkan pada yang belum di-tune intensitas bisa tersebar dan kurang terfokus.
- Frekuensi Dominan: Garis-garis horizontal pada spektrogram menunjukkan frekuensi dominan dari suara. Biola yang di-tune akan memiliki garis yang lebih tajam dan jelas pada frekuensi-frekuensi tertentu, sementara biola yang tidak di-tune bisa memiliki garis yang lebih kabur dan tersebar.
- Perubahan Waktu:  Spektrogram juga menampilkan bagaimana frekuensi berubah seiring waktu. Pada biola yang di-tune, perubahan ini akan lebih stabil dan teratur. Pada biola yang belum di-tune, perubahan frekuensi dapat lebih tidak menentu.

Secara keseluruhan, spektrogram memberikan gambaran visual tentang kualitas suara dari biola. Dengan membandingkan spektrogram biola yang di-tune dan belum di-tune, kita dapat melihat perbedaan dalam kualitas suara, stabilitas nada, dan tingkat noise. Biola yang di-tune akan memiliki spektogram yang lebih terorganisir, dengan intensitas terfokus pada frekuensi yang diinginkan.

## Kesimpulan

```
Tuliskan kesimpulan di sini (3 - 5 kalimat)
```
Berdasarkan analisis yang dilakukan, terdapat perbedaan yang signifikan antara karakteristik akustik biola tuned dan untuned. Biola tuned menunjukkan kualitas suara yang lebih baik, dengan HNR yang lebih tinggi dan distribusi frekuensi yang lebih terpusat pada frekuensi fundamental.  Hasil ini mendukung pentingnya tuning untuk mendapatkan kualitas suara biola yang optimal.
"""